name: llscheck

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
    branches:
    - main
  push:
    branches:
      - main

jobs:
  llscheck:
    runs-on: ubuntu-latest
    name: llscheck

    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: Install Neovim
      uses: rhysd/action-setup-vim@v1
      # NOTE: We need Neovim installed in order to expose the $VIMRUNTIME
      # environment variable
      with:
        neovim: true
        version: stable

    - name: Install A Lua Interpreter
      uses: leafo/gh-actions-lua@v10
      with:
        # Neovim is compiled with LuaJIT so we might as well match. But it
        # doesn't look like we can match it exactly.
        #
        # Reference:
        #    https://github.com/leafo/gh-actions-lua/issues/49#issuecomment-2295071198
        #
        luaVersion: "luajit-openresty"

    - name: Install lua-language-server
      uses: jdx/mise-action@v2
      with:
        tool_versions: |
          lua-language-server latest

    - name: Install luarocks
      uses: leafo/gh-actions-luarocks@v5

    - name: Install llscheck
      run: |
        luarocks install llscheck

    - name: Print Version
      run: |
        lua-language-server --version

    - name: Test
      run: |
        cd minimal_typechecking
        VIMRUNTIME="`nvim --clean --headless --cmd 'lua io.write(os.getenv("VIMRUNTIME"))' --cmd 'quit'`" llscheck . --no-color | grep --quiet "Total 1: 1 Warnings in 1 files" || exit 1
